Ycash testnet support
s-nomp/s-nomp pull request #139
Opened 2019-06-25 06:17 UTC by zzzpotato

2019-07-17 01:29 UTC, egyptianbman commented
@zzzpotato Can you go ahead and add the config file for mainnet?

2019-07-17 01:29 UTC, egyptianbman commented
Alternatively, we can merge this and you can create a new branch for the mainnet config.

2019-07-17 01:29 UTC, egyptianbman submitted a review, later dismissed
Thanks!

2019-07-17 11:21 UTC, zzzpotato commented
I added the mainnet configs and renamed the PR

2019-07-17 20:39 UTC, egyptianbman requested changes

2019-07-17 20:39 UTC, egyptianbman commented on coins/yec.json
> +    "peerMagic": "aae83f5f",
```suggestion
    "peerMagic": "24e92764",
```

2019-07-17 20:39 UTC, egyptianbman commented on coins/testnet/yec.json
> +    "peerMagic": "aae83f5f",
```suggestion
    "peerMagic": "fa1af9bf",
```

2019-07-18 04:00 UTC, egyptianbman approved these changes
Thanks!

2019-07-18 04:00 UTC, merged