Added editorconfig file
s-nomp/s-nomp pull request #41
Opened 2018-08-09 15:18 UTC by nettts

2018-08-09 17:57 UTC, egyptianbman requested changes

2018-08-09 17:57 UTC, egyptianbman commented on .editorconfig
> +charset = utf-8
You can probably move this to the `[*]` block.

2018-08-09 17:57 UTC, egyptianbman commented on .editorconfig
> +indent_style = space
Same with this. :)

2018-08-10 13:54 UTC, nettts commented
@egyptianbman updated.

2018-08-10 15:26 UTC, egyptianbman approved these changes
Thanks!

2018-08-10 15:26 UTC, egyptianbman commented
We can probably add the same file to the other repos.

2018-08-11 20:29 UTC, merged