Add commercium
s-nomp/s-nomp pull request #49
Opened 2018-08-14 14:05 UTC by williamsmithza

Add commercium coin to coins and pool configs

2018-08-14 14:12 UTC, egyptianbman commented
Have you tested this? I don't think this repo is compatible with CMM at this time. If I'm not mistaken, their block headers differ. Possibly other incompatibilities as well.

2018-08-14 14:34 UTC, sennevb commented
needs a change an stratum-pool for it to work, will review and do a pull request for this stratum change ASAP

2018-08-14 18:47 UTC, williamsmithza commented
Will appreciate

2018-08-18 00:07 UTC, egyptianbman commented
I don't think bitcoin interest is compatible either at this time.

2018-10-31 01:12 UTC, Gumbees requested changes
File names should be as follows

coins/testnet/symbol-or-coinname.json
coins/symbol-or-coinname.json
pool_configs/symbol-or-coinname.json
pool_configs/symbol-or-coinname.testnet.json

Were these all tested as 100% working with s-nomp? 

Thanks for your contribution!

2018-10-31 01:12 UTC, Gumbees commented on coins/bci.json
> +	"iHgcntCBzgkVfuWfKVq7gHzPzmp26uyScS",
spacing fix. 4 spaces no tabs.

2018-10-31 01:12 UTC, Gumbees commented on cmm.json
> +    "name": "Commercium",
can you lowercase the c?

2018-10-31 01:12 UTC, Gumbees commented on coins/testnet/cmm_testnet.json
> +    "name": "Commercium Testnet",
commercium_testnet

2018-10-31 01:12 UTC, Gumbees commented on config_example.json
> +        "blockRefreshInterval": 100,
please remove this. this will cause the daemons to overload like crazy by default

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/bci.json
> +        "": 1.0
0.2 is the default.

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/bci.json
> +    "enabled": true,
default is false

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/bci.json
> +        "minimumPayment": 0.1,
0.05

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/bci.json
> +        "1237": {
1234

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/bci.json
> +        "database": "btcp",
bci

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm.json
> +    "enabled": true,
false

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm.json
> +    "coin": "commercium.json",
double check the file name. should be cmm.json

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm.json
> +        "minimumPayment": 0.5,
0.05

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm.json
> +    },
0.2

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm.json
> +
remove all your addresses

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm.json
> +            "user": "user",
rpcuser

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm.json
> +            "password": "pass"
rpcpassword

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm.json
> +        "database": "mpos",
cmm

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +    "coin": "commercium_testnet.json",
file name after change testnet/cmm.json

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +
remove all your addresses

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +    "walletInterval": 1,
2.5

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +        "": 1.0
0.2

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +        "minimumPayment": 0.1,
0.05

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +        "paymentInterval": 57,
120

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +            "user": "username",
rpcuser

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +            "password": "password"
rpcpassword

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +        "3857": {
1234

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +            "diff": 0.05,
swap tls and diff lines

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +                "maxDiff": 16,
36

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +            "port": 8332,
is this the correct default port for cmm testnet?

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +                "port": 8332,
is this the correct default port for cmm testnet?

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/cmm_testnet.json
> +        "database": "cmm",
cmm_testnet

2018-10-31 01:12 UTC, Gumbees commented on cmm.json
> +}
we need to add the block explorer before this line. You can use # if there is none or it is NA

2018-10-31 01:12 UTC, Gumbees commented on pool_configs/examples/bci.json
> +            "diff": 0.05,
swap tls and diff lines

2018-10-31 01:12 UTC, Gumbees commented on coins/testnet/cmm_testnet.json
> +}
again the explorer part is needed.

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +    "walletInterval": 1,
2.5

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +        "user": "root",
me

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +        "password": "mysqlpass",
mypass

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +        "checkPassword": false,
true

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +        "autoCreateWorker": true
false

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm_testnet.json
> +        "port": 19333,
correct port is needed. this would be the daemon peer port.

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/bci.json
> +            "user": "",
rpcuser

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/bci.json
> +            "password": ""
rpcpassword

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/bci.json
> +            "user": "",
rpcuser

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/bci.json
> +            "password": ""
rpcpassword

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +            "user": "user",
rpcuser

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +            "password": "pass"
rpcpassword

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +        "3333": {
1234

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +            "diff": 1,
diff 0.05 and swap tls and diff lines

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +                "minDiff": 0.5,
0.05

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +                "maxDiff": 1024768,
36

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +            }
double check the spacing in the entire difficulty block. 4 spaces no tabs.

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm.json
> +        "port": 19333,
this port needs to be the peer port of the daemon

2018-10-31 01:12 UTC, nettts commented on pool_configs/examples/cmm_testnet.json
> +        }
please double check spacing.

2018-10-31 01:52 UTC, Gumbees requested changes
lets make everything lowercase in naming in these config files as well.

2018-10-31 01:52 UTC, nettts commented on pool_configs/examples/cmm.json
> +
poold block needs to be here.

2018-10-31 01:52 UTC, nettts commented on pool_configs/examples/cmm_testnet.json
> +
poolId block needs to be here.

2018-12-11 01:44 UTC, egyptianbman commented
Closing this as there doesn't seem to be interest in completing the PR.

2018-12-11 01:44 UTC, closed without merging