SafeCash (Testnet) Added
s-nomp/s-nomp pull request #50
Opened 2018-08-14 17:24 UTC by hashtobewild

This commit adds SafeCash (Testnet) support and also some minor changes to messages to make debugging easier.

2018-08-18 00:05 UTC, egyptianbman requested changes
Thank you for providing this. I haven't had a chance to verify the ports are all correct yet but I left a couple of requests for now.

2018-08-18 00:05 UTC, egyptianbman commented on coins/safecash.json
> +    "foundersRewardAddresses": ["SPfqCriDDxsaH854z3YHigCNUPfSdN3sr1","SaSmUn7LkjmV2WUH1dKFK1xZR1FMRT4qrn","SbfnZN1rPdFq4WsfUUjxphGFcfEits7JXH","SSW62dCjdCxNbKiZdmJh5GLepauY1J1rXU","SW9GN4tZVfPftAQvGm
Can you fix the alignment in this file? We've put an https://editorconfig.com [file](https://github.com/s-nomp/s-nomp/blob/master/.editorconfig) in the repo that should help with styling if your IDE supports it. Primarily, four space indentation, expand arrays and objects (i.e. lines 18-22 not being on one line), etc. Feel free to check out the other configs for ideas.

2018-08-18 00:05 UTC, egyptianbman commented on pool_configs/examples/safecash.json
> +        "5654": {
Can you set this to 1234?

2018-08-18 00:05 UTC, egyptianbman commented on pool_configs/examples/safecash.json
> +        "database": "zer_testnet",
Can you set this to scash_testnet?

2018-09-17 00:56 UTC, nettts commented
@egyptianbman all configs tested. Merge after https://github.com/s-nomp/node-stratum-pool/pull/12

2018-09-21 09:12 UTC, egyptianbman requested changes
A few last minor requests; thanks!

2018-09-21 09:12 UTC, egyptianbman commented on coins/genesis.json
> +            "N": 192,
Can you fix the alignment here? Should be four spaces per tab

2018-09-21 09:12 UTC, egyptianbman commented on coins/testnet/genesis.json
> +            "N": 192,
Same here with the spaces

2018-09-21 09:12 UTC, egyptianbman commented on coins/genesis.json
> +        "blockURL": "http://explorer.genesisnetwork.io/block",
I believe these need the trailing slash.

2018-09-21 09:12 UTC, egyptianbman commented on coins/testnet/genesis.json
> +        "blockURL": "https://testnet.genesisnetwork.io/block",
I believe these need the trailing slash.

2018-09-21 09:12 UTC, egyptianbman commented on libs/paymentProcessor.js
> +                logger.error(logSystem, logComponent, 'Error with payment processing daemon (validateAddress) ' + JSON.stringify(result.error));
Thank you for these updates!

2018-09-21 09:12 UTC, egyptianbman commented on pool_configs/examples/genesis.json
> +    "enabled": true,
Default enabled to `false`

2018-09-21 09:12 UTC, egyptianbman commented on pool_configs/examples/genesis.testnet.json
> +    "enabled": true,
Default enabled to `false`

2018-09-22 07:36 UTC, egyptianbman approved these changes
Thank you!

2018-09-22 07:37 UTC, merged