Added 2 new coins.
s-nomp/s-nomp pull request #63
Opened 2018-09-10 10:35 UTC by globaltoken

Hey,

I added 2 new Coins. We have Globaltoken Zhash & Globaltoken Equihash, because we use Multialgorithm.

Greetings,
Pawel

2018-09-11 14:29 UTC, nettts commented
👍 for the looks. needs tested by one of us. can you add testnet configs so we can throw it up and test? @globaltoken

2018-09-11 14:31 UTC, globaltoken commented
@nettts The hardfork is not released yet.
I will test it.

2018-09-29 16:11 UTC, sennevb commented
seems cool, but node-stratum-pool needs to be merged with snomp :-) :-D

2018-09-29 16:45 UTC, egyptianbman requested changes

2018-09-29 16:45 UTC, egyptianbman commented on package.json
> +        "stratum-pool": "git+https://github.com/globaltoken/snomp-stratum-pool.git"
This isn't an option. You'll need to create a PR to https://github.com/s-nomp/node-stratum-pool.git to support this coin and restore the original value.

2018-09-30 12:19 UTC, globaltoken commented on package.json
> +        "stratum-pool": "git+https://github.com/globaltoken/snomp-stratum-pool.git"
@egyptianbman I will restore it

2018-09-30 12:23 UTC, globaltoken commented
Alright, everything is working with this commit. In theory Bitcoin Gold should work with this Code part as well, because it is a direct Bitcoin Fork, and not Zcash based. I tested this for Globaltoken alone and with @sennevb who integrated GLT successfully into his Pool.

The stratum pull: https://github.com/s-nomp/node-stratum-pool/pull/20

If you have any more questions, let me know about it.
Cheers,

2019-12-13 13:39 UTC, zzzpotato commented
This appears abandoned. Closing...

2019-12-13 13:39 UTC, closed without merging