Added Bithereum Testnet and Mainnet pool configuration
s-nomp/s-nomp pull request #95
Opened 2018-11-20 19:38 UTC by dondreytaylor

Added Bithereum (BTH) as an available coin. The mainnet explorer links will be fully functional a little after December 7th, when the snapshot is made. Testnet links are otherwise live.

2019-01-31 04:10 UTC, egyptianbman requested changes
Hey @dondreytaylor, I apologize for the delay. I tried mining to BTH but ran into issues with the stratum. I have a patch that I'll push up to https://github.com/s-nomp/node-stratum-pool which resolves the issue with mining.

I did run into another issue, however. The pool submitted what it thought was a valid block but the block was rejected by the node. The only output I got from the node is:
```
2019-01-30 13:26:20 ERROR: ProcessNewBlock: AcceptBlock FAILED
```

2019-01-31 04:15 UTC, dondreytaylor commented
It's okay @egyptianbman, figured you may have been pretty busy. I'm going to try running it again on my end. I think I s-nomp using the node-stratum that we forked. I'll compare the node-stratums and try submitting a block using s-nomp to see what I can find.

2019-01-31 04:31 UTC, egyptianbman commented
Thanks. For reference, this is the change that enables mining to work: https://github.com/s-nomp/node-stratum-pool/pull/33

This doesn't resolve the issue with submitting blocks, however. Also, this PR is missing example pool configs. Can you copy one of the files in this directory and update it for BTH? You can keep most things the same, just update ports, comments as needed (i.e. if I'm not mistaken, BTH doesn't require shielding, right?, etc).  Let me know if you need any help. You can also reach me on Discord which will usually yield a faster response.

2019-01-31 04:34 UTC, dondreytaylor commented
Okay, this is great info, I'll be sure to reference that PR. Yes, BTH doesn't require shielding that's correct. Will be in touch on discord if I can't reach you here. I'll update this PR tomorrow and then reach back out after testing, for sure. Thanks.

2019-01-31 04:35 UTC, egyptianbman commented
I forgot to mention that with that PR, you'll need to add `"subsidyMultipleOfSatoshi": 1,` to the coin config file.

2019-01-31 04:36 UTC, dondreytaylor commented
> I forgot to mention that with that PR, you'll need to add `"subsidyMultipleOfSatoshi": 1,` to the coin config file.

Ah okay, I'll add that in.

2019-01-31 04:36 UTC, egyptianbman commented
Thank you!

2019-07-06 08:38 UTC, egyptianbman commented
Closing as this PR seems to be abandoned. Please reopen if that's not the case.

2019-07-06 08:38 UTC, closed without merging