add bitzec BZC
s-nomp/s-nomp pull request #96
Opened 2018-11-23 15:01 UTC by bitzec

bitzec.org

2018-11-25 05:21 UTC, egyptianbman requested changes

2018-11-25 05:21 UTC, egyptianbman commented on coins/bzc.json
> +	            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG",
```suggestion
	            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG",
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG",
```

2018-11-25 05:21 UTC, egyptianbman commented on coins/bzc.json
> +            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG",
Just confirming these addresses should be repeated like this?

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +    "address": "[MINING_ADDRESS]",
```suggestion
    "address": "",
```

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +    "zAddress": "[SHIELDING_PRIVATE_ADDRESS]",
```suggestion
    "zAddress": "",
```

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +    "tAddress": "[PAYMENT_TRANSPARENT_ADDRESS]",
```suggestion
    "tAddress": "",
```

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +        "[YOUR_POOL_FEE_ADDRESS]": [YOUR FEE IN PERCENTS(1 for 1%)]
```suggestion
        "": 0.2
```

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +            "user": "[DAEMON_RPC_USER]",
```suggestion
            "user": "rpcuser",
```

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +            "password": "[DAEMON_RPC_PASSWORD]"
```suggestion
            "password": "rpcpassword"
```

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +            "port": [8733],
```suggestion
            "port": 8732,
```

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +            "user": "[DAEMON_RPC_USER]",
```suggestion
            "user": "rpcuser",
```

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +            "password": "[DAEMON_RPC_PASSWORD]"
```suggestion
            "password": "rpcpassword"
```

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +        "database": "zec",
```suggestion
        "database": "bzc",
```

2018-11-25 05:21 UTC, egyptianbman commented on coins/bzc.json
> +    "overwinter": true,
If sapling is activated, there is no need for this.

```suggestion
```

2018-11-25 05:21 UTC, egyptianbman commented on coins/bzc.json
> +    "foundersRewardAddressChangeInterval": 17709,
Can you verify these values are accurate?

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +        "3036": {
Please adjust to match https://github.com/s-nomp/s-nomp/blob/master/pool_configs/examples/zec.json#L48

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +            "port": [8733],
```suggestion
            "port": 8732,
```

2018-11-25 05:21 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +        "port": 19333,
```suggestion
        "port": 8733,
```

2018-11-25 13:05 UTC, bitzec commented on coins/bzc.json
> +	            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG",
"t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 0*/
            "t3ZwokSicGHQhF7nuPVzKxTfm5qHVbXV5vS", /* main-index: 1*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 2*/
            "t3MpjbqV1f6dQcnXjBbdYCzDa87XQYuTbWz", /* main-index: 3*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 4*/
            "t3NdSKHyB7siGWGzXy6NLWNMdjF6wwWZjxy", /* main-index: 5*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 6*/
            "t3dYeSR5bNsCXtGwythocQGxfvChetbBbXj", /* main-index: 7*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 8*/
            "t3bTvatHrv7CgtNY8ZVtqeYrRsHcDGUBqSg", /* main-index: 9*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 10*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 11*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 12*/
            "t3fTavgWgerUopjuYyJLPi8mQDhcFhDRvDa", /* main-index: 13*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 14*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 15*/
            "t3MpjbqV1f6dQcnXjBbdYCzDa87XQYuTbWz", /* main-index: 16*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 17*/
            "t3fHgXgwhP4UjxCLZwyiaBNPVWrzYL1GffL", /* main-index: 18*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 19*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 20*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 21*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 22*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 23*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 24*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 25*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 26*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 27*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 28*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 29*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 30*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 31*/
            "t3aaW4aTdP7a8d1VTE1Bod2yhbeggHgMajR", /* main-index: 32*/
            "t3PPMGfYJ7FXzvRxNefS21Hgh8Fqp8Es93e", /* main-index: 33*/
            "t3NTfpUNJ1au66E1hvqNwFzL4qdvZp2Rwfk", /* main-index: 34*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 35*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 36*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 37*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 38*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 39*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 40*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 41*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 42*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 43*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 44*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 45*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 46*/
            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG", /* main-index: 47*/

2018-11-25 13:14 UTC, bitzec commented on coins/bzc.json
> +    "foundersRewardAddressChangeInterval": 17709,
consensus.nSubsidyHalvingInterval = 13000001;
   
"foundersRewardAddressChangeInterval": 270833
48 founders reward addresses  
13000001/48 = 270883
calculation 

zcash: 

    "maxFoundersRewardBlockHeight": 849999,
    "foundersRewardAddressChangeInterval": 17709,
48 founders reward addresses  
849999/ 17709 =47.9

2018-11-25 21:51 UTC, bitzec commented on coins/bzc.json
> +            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG",
yes thats ok

2018-11-25 21:52 UTC, bitzec commented on pool_configs/examples/bzc.json
> +        "3036": {
forwarded config from pool  , that is working

2018-11-26 04:04 UTC, egyptianbman commented on coins/bzc.json
> +    "foundersRewardAddressChangeInterval": 17709,
Thanks for confirming!

2018-11-26 04:04 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +        "3036": {
Yes, this is the pool port. We keep them all the same in every config file so that supporting a new coin is predictable.

2018-11-26 04:04 UTC, egyptianbman commented on pool_configs/examples/bzc.json
> +    "enabled": true,
```suggestion
    "enabled": false,
```

2018-11-26 04:05 UTC, egyptianbman commented on coins/bzc.json
> +	            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG",
Can you remove the tab at the beginning of this line?

2018-11-26 11:30 UTC, bitzec commented on coins/bzc.json
> +	            "t3SAe5q2qTaZyFvQwGDTRLYGVtNpzhi9EyG",
Ok

2018-11-26 12:57 UTC, bitzec reviewed
final edit

2018-12-10 20:19 UTC, Gumbees requested changes
1 change. Then this can be approved.

2018-12-10 20:19 UTC, nettts commented on pool_configs/examples/bzc.json
> +        "port": 1234,
3306

2018-12-10 20:19 UTC, nettts commented on pool_configs/examples/bzc.json
> +
I'm assuming you tested out these difficulties already and are recommended for this coin?

2018-12-10 22:26 UTC, bitzec commented on pool_configs/examples/bzc.json
> +        "port": 1234,
3306

2018-12-10 22:26 UTC, bitzec commented on pool_configs/examples/bzc.json
> +
seem to work ok  on pools

2018-12-10 22:26 UTC, bitzec commented
change done 

thanks

2018-12-10 22:26 UTC, bitzec commented on pool_configs/examples/bzc.json
> +        "port": 1234,
change done

2018-12-25 02:01 UTC, egyptianbman approved these changes
Thanks!

2018-12-25 02:01 UTC, merged

2018-12-25 11:14 UTC, bitzec commented
Thank you